baseurl = "https://jovial-pasteur-e3b9cf.netlify.com/"
title = "Admongrel Blog"
author = "Admongrel"
canonifyurls = true
paginate = 3
theme = "aether"

[params]
brand = "Admongrel"
description = "Admongrel Blog"
bgimg = "img/bg.png"
